CREATE TABLE school(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(60) NOT NULL
);

CREATE TABLE class(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  school_id BIGINT REFERENCES school(id) NOT NULL
);

CREATE TABLE classRoom(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  school_id BIGINT REFERENCES school(id) NOT NULL
);

CREATE TABLE fanlar(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  title VARCHAR(60) NOT NULL,
  class_id BIGINT REFERENCES class(id) NOT NULL
);

CREATE TABLE tasks(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  maxMark BIGINT NOT NULL,
  fan_id BIGINT REFERENCES fanlar(id) NOT NULL
);

CREATE TABLE teacher(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  exprience BIGINT NOT NULL,
  username VARCHAR(60) NOT NULL,
  password VARCHAR(60) NOT NULL,
  fan_id BIGINT REFERENCES fanlar(id) NOT NULL
);

CREATE TABLE lessonTable(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  lesson_time DATE NOT NULL,
  teacher_id BIGINT REFERENCES teacher(id) NOT NULL,
  classRoom_id BIGINT REFERENCES classRoom(id) NOT NULL
);

CREATE TABLE attendance(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  lessonTable_id BIGINT REFERENCES lessonTable(id) NOT NULL,
  has BOOLEAN NOT NULL
);

CREATE TABLE parents(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  username VARCHAR(60) NOT NULL,
  password VARCHAR(60) NOT NULL,
)

CREATE TABLE student(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  course BIGINT NOT NULL,
  parent_id BIGSERIAL REFERENCES parents(id) NOT NULL,
  username VARCHAR(60) NOT NULL,
  password VARCHAR(60) NOT NULL,
  class_id BIGSERIAL REFERENCES class(id) NOT NULL
);

CREATE TABLE daily(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  lessonTable_id BIGINT REFERENCES lessonTable(id) NOT NULL,
  student_id BIGINT REFERENCES student(id) NOT NULL
);

CREATE TABLE marks(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  mark BIGINT NOT NULL,
  student_id BIGSERIAL REFERENCES student(id) NOT NULL,
  tasks_id BIGSERIAL REFERENCES tasks(id) NOT NULL
);
